* Purpose

Implement a simple encoder/decoder of Morse code.

* Building

You gonna need a C++ compiler complacent with the fourteenth standard
(/C++14/) and maybe CMake if you will.

*** Building with CMake

To build with CMake it is pretty straight forward, you just need to do:

#+BEGIN_SRC bash
cmake ./
make
#+END_SRC

*** Building without CMake

You can either compile it directly with the compiler in hands

#+BEGIN_SRC
g++ -Wall -pedantic -std=c++14 src/main.cpp src/morse.cpp -o bin/morse.out
#+END_SRC

Or you can open the source files on a IDE of choice and compile them.

* What you can do with it?

Encode latin words to morse, decoding morse code is also possible but you should
have in mind that each morse character should be separated by a space.

*** Examples

#+BEGIN_SRC bash
$ ./bin/morse --encode Rafael Campos Nunes
Result: .-..-..-..-..-.. -.-..---.--.---... -...--.....
#+END_SRC

The encode function just separate words and not letters, so it should be a
bit difficult to decode the message.

On the other hand decoding information will give you a scrambled result, with
each letter separated by a space character.

#+BEGIN_SRC bash
$ ./bin/morse --decode .-. .- ..-. .-
Result: r a f a
#+END_SRC
